### ISSUE TITLE
how to use your code?

### ISSUE THREAD

**Issue by IamMegatron2025** [ale93111/FCNN_cell#1]
hello, I am a fresh hand for cell. I want to use your code to test an image.  but how to do this? can you provide some examples?

Thank you in advance!

**Comment by ale93111** [comment]
Hello. I'm glad you have taken an interest in this project. Please consider that this code uses the OpenCV and Caffe libraries and to use it you should be familiar with them since this code requires you to have an hands-on approach: you will need to modify some of the code in order to get it to work (for example setting the path). 

That said there are various scripts available to you:
- the main script is network.py which generates the train/test/solver .prototxt files for the caffe network model
- hdf5.py is a simple script that gathers your images into an .hdf5 file that caffe can use to train the network
- data_augmentation.py does the data augmentation (on the single images, not the .hdf5 set) of the training set as described in the report
- net_evaluation.py load the trained model of the network and evaluates the network on the entire test dataset to get the performance parameters

After generating the .prototxt files you should train the network using Caffe and then you can use net_evaluation.py to evaluate the network. I've uploaded for you a small dataset of images that you can use to train/test and a snapshot of the trained network.

**Comment by IamMegatron2025** [comment]
@ale93111 thankyou for your response. Now I know how to use your code. You said you will upload a small dataset for me, but I can see it.
looking for your response~

**Comment by ale93111** [comment]
@IvyGongoogle The dataset is called "test.h5" and it's in the standard HDF5 format. You can find it in the last commit.

**Comment by IamMegatron2025** [comment]
@ale93111 my god. I see it !!
sorry to bother you again. Can you provide image data, rather than the h5 format file.
thank you very much~~

**Comment by IamMegatron2025** [comment]
@ale93111 besides, when I run the `net_evaluation.py`,it shows error:

```
net_evaluation.py:64: RuntimeWarning: divide by zero encountered in long_scalars
  precision   = tp/(tp + fp)
('AUC: ', 0.0)
('\n', 'true_positive: ', 0, '\n', 'true_negative: ', 1611086, '\n', 'false_positive: ', 0, '\n', 'false_negative: ', 191154)
net_evaluation.py:104: RuntimeWarning: divide by zero encountered in long_scalars
  precision   = tp/(tp + fp)
net_evaluation.py:109: RuntimeWarning: invalid value encountered in divide
  mccoeff     = (tp*tn - fp*fn)/(np.sqrt(tp+fp)*np.sqrt(tp+fn)*np.sqrt(tn+fp)*np.sqrt(tn+fn))
('\n', 'specificity: ', 1, '\n', 'precision:   ', 0, '\n', 'recall:      ', 0, '\n', 'fall out:    ', 0, '\n', 'accuracy:    ', 0, '\n', 'fscore:      ', 0, '\n', 'mccoeff:     ', nan, '\n', 'AUC:         ', 0.0)
```
how to fix it?

**Comment by ale93111** [comment]
@IvyGongoogle I've uploaded the image data for you. The error is just a runtime warning that happens because the values of tp or fp can be 0 when using threshold values too close to 0 or 1. You can try changing the range of threshold values of the grid search to find the best threshold to avoid the error.

**Comment by IamMegatron2025** [comment]
@ale93111 sorry to reply you too late. I change the line `tresholds = np.linspace(0,1,100)`. But how to set the tresh in  `tresh = tresholds[5] #best mcc` ? can you give some advices?

**Comment by ale93111** [comment]
Just select the threshold of probability (from the array of thresholds) that gives you the best parameters. Then this value is used to evaluate the network.

**Comment by IamMegatron2025** [comment]
@ale93111 thankyou very much!
